// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaNey3D_L3_pn7jWR9zeWoX8WA5COrJlA',
    appId: '1:989679624387:web:9f96451276879d0aa78276',
    messagingSenderId: '989679624387',
    projectId: 'mobile-its',
    authDomain: 'mobile-its.firebaseapp.com',
    storageBucket: 'mobile-its.firebasestorage.app',
    measurementId: 'G-EM95NWZW7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAStB0dCP86L8nqdm5AgBe4bQDYgJSwT98',
    appId: '1:989679624387:android:6175c657893effa6a78276',
    messagingSenderId: '989679624387',
    projectId: 'mobile-its',
    storageBucket: 'mobile-its.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_IcgIMiSNrNJ7tD5KI0rNOXfqrhoS2LA',
    appId: '1:989679624387:ios:1e1437ecb968a26aa78276',
    messagingSenderId: '989679624387',
    projectId: 'mobile-its',
    storageBucket: 'mobile-its.firebasestorage.app',
    iosBundleId: 'com.example.taskmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_IcgIMiSNrNJ7tD5KI0rNOXfqrhoS2LA',
    appId: '1:989679624387:ios:1e1437ecb968a26aa78276',
    messagingSenderId: '989679624387',
    projectId: 'mobile-its',
    storageBucket: 'mobile-its.firebasestorage.app',
    iosBundleId: 'com.example.taskmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaNey3D_L3_pn7jWR9zeWoX8WA5COrJlA',
    appId: '1:989679624387:web:5f0759de9abd6c59a78276',
    messagingSenderId: '989679624387',
    projectId: 'mobile-its',
    authDomain: 'mobile-its.firebaseapp.com',
    storageBucket: 'mobile-its.firebasestorage.app',
    measurementId: 'G-KFSS4NTXLM',
  );
}
